spring:
  datasource:
    url: jdbc:h2:./database/prod
    username: ${database.username}
    password: ${database.password}
  #    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: ${security.username}
      password: ${security.password}