spring.servlet.multipart:
  enabled: true
  file-size-threshold: 2KB
  max-file-size: 7MB
  max-request-size: 10MB

ssp:
  confirmation-emails:
    - maksim.patapenka@gmail.com
  delivery-prices:
    # Price in BYN
    cash-on-delivery: 3
  image-storage-location: ./images