underwear-shop:
  confirmation-emails:
    - maksim.patapenka@gmail.com
  delivery-prices:
    cash-on-delivery: 3 # BYN
  image-storage-location: ./images
  meta-info:
    title: Underwear-Shop REST API
    description: Provides REST API to interact with Underwear-Shop web application
    version: 1.0.0
    contacts:
      app-name: Underwear-Shop

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      maximum-pool-size: 3
  servlet.multipart:
    max-file-size: 7MB
  mvc:
    static-path-pattern: /resources/**
  messages:
    basename: languages/messages
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.transport.protocol: smtp